### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RowanUtrecht**
Added my Osmo address for the Bounty! Thx

### CODE REVIEW

**Comment by LL-Cosmo** [comment]
Added too, thanks Jae appreciated 🙏

**Comment by RowanUtrecht** [comment]
Any idea when the bounty will be paid?

________________________________

**Comment by RowanUtrecht** [comment]
@jaekwon 
Hi Jae! Any updates? Looks like you've gone offline for a while. Hope you are OK!

**Comment by jaekwon** [comment]
sending atom address instead as requested.
$8.20 OSMO, $38.00 ATOM, and 20% penalty for being so late.
5000 * 3.0 / 24.0 * 8.2 / 38.00 * 1.2, 161.84 ATOMs.

**Pull request merged**
