### PR TITLE
Bounty #6 Calculate the delegations of the ICF

### PR DESCRIPTION
**Pull request by LL-Cosmo**
* ### [Research and weightings of ICF multisig accounts](https://github.com/gnolang/bounties/issues/18)

  * **@LL-Cosmo  Cosmos address** for the bounty:
cosmos14ypel6pjxzvygwmm7quq87v9rntqkpvuxmqvrr

* ### ICF Cosmos multisig addresses:

cosmos1z8mzakma7vnaajysmtkwt4wgjqr2m84tzvyfkz

cosmos1unc788q8md2jymsns24eyhua58palg5kc7cstv

  
*  **Source:**

https://github.com/cosmos/mainnet/blob/master/accounts/icf/multisig.json

### CODE REVIEW

**Comment by LL-Cosmo** [comment]
Research and weightings

https://github.com/gnolang/bounties/pull/20

**Comment by LL-Cosmo** [comment]
* This repository summarizes the Interchain Foundation's approach to delegating its ATOMs.
https://github.com/interchainio/delegation

* ICF funding reports 2018-2019
https://github.com/interchainio/funding/tree/master/projects

* ICF Delegations till 4/2020
https://github.com/interchainio/delegation/tree/master/delegations

* Original Cosmosplan by Cosmos whitepaper
https://github.com/cosmos/cosmos/blob/master/PLAN.md

* https://interchain.io/funding/

**Comment by piyush4** [comment]
Hi,

I have written a script in Python using mintscan. 

The link to the GitHub repository is here:
[Bounty 6 Python](https://github.com/piyush4/bounty-6/)

The script calculates the current delegations (the amount, validator name along with validator website addresses, if available) of ICF from mintscan and stores them in a CSV file. In case, there are any rewards. Following is my cosmos address:
cosmos122taa46qrdv22ryk6v9wvs285y24q9z2ydf4k4

**Comment by jaekwon** [comment]
Hey all, I need a PR that mimics this: https://github.com/gnolang/bounties/blob/main/bounties/001_cosmoshub_blockchain_data/README.md. Mind creating a complete PR like that please?

**Comment by LL-Cosmo** [comment]
> Hey all, I need a PR that mimics this: https://github.com/gnolang/bounties/blob/main/bounties/001_cosmoshub_blockchain_data/README.md. Mind creating a complete PR like that please?

https://github.com/gnolang/bounties/blob/c79070b65b9a2bd644b9fdbdd0b794cefc7f7cc8/bounties/006_icf_delegations/README.md


Thanks to @piyush4 for making this PR

**Comment by jaekwon** [comment]
paid to each, thank you!

**Comment by LL-Cosmo** [comment]
> paid to each, thank you!

Thank you 🙏

**Pull request closed without merging**
