### PR TITLE
Update README.md bounty#1 LL-Cosmo Osmo address added

### PR DESCRIPTION
**Pull request by LL-Cosmo**

### CODE REVIEW

**Comment by LL-Cosmo** [comment]
Thank you Jae 🙏
Appreciated

**Comment by jaekwon** [comment]
Hi, I just paid out PR #16, but I cannot make an osmo payment just today, so I will wait until you confirm the equivalent ATOM address, and I will pay ATOMs, or please wait for OSMO soon.  I'll also add a 20% penalty for being so late.  Cheers

**Comment by LL-Cosmo** [comment]
Thanks Jae you're the best!
No worries

Heres my Atom address which you can use:

cosmos1aj6j80kcqmphun5tljxn72hw5u37v6x64kauv6

**Comment by jaekwon** [comment]
>>> 5000 * 1.0 / 24.0 * 8.2 / 38.00 * 1.2
53.95 ATOMs

**Pull request merged**
